# Generated by Django 3.0.6 on 2020-05-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('face_id', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=100)),
                ('collection_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rekognition.Collection')),
            ],
        ),
    ]
