# Generated by Django 3.0.6 on 2020-05-05 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rekognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='collection_id',
            field=models.ManyToManyField(to='rekognition.Collection'),
        ),
        migrations.AddField(
            model_name='person',
            name='image_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
