# Generated by Django 3.0.6 on 2020-05-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekognition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='collection_id',
            new_name='collection_id_id',
        ),
    ]
