# Generated by Django 3.0.6 on 2020-05-10 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rekognition', '0002_auto_20200506_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='face_metadata',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
